version: '3.8'

services:
  todolist_expresjs:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 9182:5151
    depends_on:
      - todolist_db
      - todolist_migration
    env_file:
      - .env.production
    command: sh -c "npm run start:prod"
    volumes:
      - todolist_volume:/app/node_modules
      - .:/app

  todolist_migration:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - todolist_db
    env_file:
      - .env.production
    command: sh -c "npm run db:migrate:prod && npm run db:seed:prod"
    restart: on-failure

  todolist_db:
    image: postgres:14
    ports:
      - 5437:5432
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=todolist

volumes:
  todolist_volume: