name: deploy todolist nodejs

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Deploy to vps
        uses: appleboy/ssh-action@master
        with:
          host: 191.96.57.57
          username: root
          password: Kin@n-g1nGD3mon
          script: |
            cd /root/Bingle-Shop
            git pull origin dev-new
            docker compose down
            docker compose up -d    